repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

#  - repo: https://github.com/PyCQA/pylint
#    rev: pylint-2.4.4
#    hooks:
#      - id: pylint
#        args: ["--errors-only","--rcfile=.pylintrc"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [python]
        entry: "python -m pylint --rcfile=.pylintrc --errors-only"
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        types: [python]
        entry: "mypy --ignore-missing-imports"
